//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

//score
export const UPDATE_DRAW_SCORE = 'UPDATE_DRAW_SCORE';
export const UPDATE_MACHINE_SCORE = 'UPDATE_MACHINE_SCORE';
export const UPDATE_USER_SCORE = 'UPDATE_USER_SCORE';
